language: php

# Docker on Travis needs sudo
sudo: True

before_script:
  - pushd app-context
  - cp .env.example .env
  - docker run --rm -v $(pwd):/app composer/composer install --no-interaction --prefer-source
  - popd

  - pushd docker-context
  # Run our services in a detached manner
  - docker-compose up -d 
  - docker-compose exec -T app php artisan key:generate
  - docker-compose exec -T app php artisan optimize

script:
  - docker-compose exec -T app vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - docker-compose exec -T app bash <(curl -s https://codecov.io/bash)
  - popd

notifications:
  notifications:
    slack: agilesoftwarecourse:s88h27xWCEDdojbTRgquomEv
  on_success: never
