version: '2'
services:

  # The Application
  app:
    build:
      context: ./docker-context
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./app-context/:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./docker-context
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8888:80

  # The Databases
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    ports:
        - "3307:3306"

volumes:
  dbdata:
